### PR TITLE
Partner platform/component pull request

### PR DESCRIPTION
**Pull request by betzw**
Prepare handover to @bcostm

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can you clean the git history or I can merge squash it. 
This updates drivers to 1.3.2, and there's PR here updating it to v1.4.0. Is this planned?

**Comment by betzw** [comment]
I would squash it.
Also because I did some changes which are not in the mainline Cube distro.
In future @bcostm will maintain the port and bring Cube and this mbed module in synch.

**Comment by 0xc0170** [comment]
There's #5 which updates it to the newer version than this one. Please look at it.

**Comment by betzw** [comment]
You can use #5!
I'll close the PR.

**Pull request closed without merging**
