### PR TITLE
Fixed SDIO_DataConfig for u-blox Wi-Fi driver

### PR DESCRIPTION
**Pull request by andreaslarssonublox**
Clock frequency >= 24MHz and compiler optimization cause DPSM not to function correctly.
STA register is not properly updated to indicate end of transfer.
By delaying until SDIO_DPSM_ENABLE is unset, this at least works for 24MHz, though
48MHz still hangs.

### CODE REVIEW

**Comment by 0xc0170** [comment]
@bcostm

**Comment by bcostm** [comment]
Hi,
Thanks for reporting this issue. As it is related to the ST HAL driver and not the mbed code, I suggest to post this issue in the STM32 forum:
[https://my.st.com/public/STe2ecommunities/mcu/Lists/cortex_mx_stm32/AllItems.aspx

**Comment by 0xc0170** [comment]
@bcostm What's the issue report/fix flow for this repository? We might want to state that in the Readme.

**Comment by bcostm** [comment]
Yes it is a good idea. Because if we modify this repo, the next time someone will update it with a new version, he will erase all the changes made and we will not see it...

But I was thinking of something: add a new folder (for example ST_HAL_FIX) in the folder 
mbed\targets\cmsis\TARGET_STM\TARGET_STM32Fx
We will put inside all ST HAL files that need to be modified. These files will overwrite the official files. If someone update the ST HAL official files with a new version, we'll still have the fix files. But time to time it will be necessary to make a diff with the official files and check if the modifications are not included. I don't know if it makes sense ? It is an idea...

**Comment by andreaslarssonublox** [comment]
The fix is not 100% so we have chosen to solve it in the upper layer instead.

**Pull request closed without merging**
