### PR TITLE
Update to STM32CubeF4 V1.3.2

### PR DESCRIPTION
**Pull request by bcostm**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Although it's closed, How does this differ from #5 ? Can you @bcostm test that one, if it's up to date version of cube?

**Comment by bcostm** [comment]
Yes I have close it because I didn't see the previous PR before I send mine... I will check the last version.

**Comment by betzw** [comment]
@bcostm even if the commit in #5 talks about a version far beyond the latests drivers?!?

**Comment by 0xc0170** [comment]
That PR had a wrong name it seems, the version there is v1.4.0, you can pinpoint it there

**Comment by bcostm** [comment]
There is a misunderstanding of the different versions used. It is the same as the modules we use in mbed. Today we have the STM32CubeF4 "module" which has the version 1.9.0. Inside there is the STM32F4 HAL driver "module" and this one has the version 1.4.1...

**Comment by betzw** [comment]
It seems as this is not clear to everybody ... including myself ;-)

**Comment by bcostm** [comment]
If you look at the release_notes.html file present in the root folder of STM32CubeF4 package you will see all the different "modules":
image

**Comment by betzw** [comment]
Thanks a lot @bcostm.
I think in ST need to be really careful about using these release/version numbers in order not to confuse people. I would propose to use the terms "package release number" vs "module version number".
What do you think?

**Comment by bcostm** [comment]
In fact, all the files which are put in the mbed-hal-st-stm32cubef4 module are those present in the  **STM32F4xx HAL** driver. This is why I don't like to use the version of the STM32CubeF4 package and I prefer to use the STM32F4xx HAL driver version. Also in the next STM32CubeF4 package, which could be for example V1.10.0, the STM32F4xx HAL driver will keep the same version. 

And to be more precise, I would prefer to rename this module mbed-hal-st-**stm32f4xxhal** instead...

**Comment by 0xc0170** [comment]
> And to be more precise, I would prefer to rename this module mbed-hal-st-stm32f4xxhal instead... 

You can create an issue for this module to be renamed. However this might be late for the upcoming release, can happen for the next

**Comment by bcostm** [comment]
OK. See Issue #7

**Pull request closed without merging**
